### PR TITLE
feat: md

### PR DESCRIPTION
**Pull request by NeonGamerBot-QK**
add support for
- links
- bold text
if there is any other things that arent supported ill add it on here.

### CODE REVIEW

**Comment by NeonGamerBot-QK** [comment]
@GingerGigiCat

**Comment by GingerGigiCat** [comment]
Surely there should be a way for it to run in reverse? If is_slack is False?

**Comment by NeonGamerBot-QK** [comment]
Discord doesn’t usually add extra stuff to links on discord; I can add support for hypr links if you want

**Comment by GingerGigiCat** [comment]
That would be good, also, the else statement in convertBold doesn't seem to change anything unless I'm mistaken?

**Pull request merged**
